import Head from 'next/head';
import Image from 'next/image';
import { StyledDiv } from '../styles/index.styles';

export default function Home() {
  return (
    <StyledDiv>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>hello from git</h1>
    </StyledDiv>
  );
}

// export async function getStaticProps() {

//   return {props: {loadedData: data}}
// }
